---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: booleanFlagRomain

enabled: true

stickinessProperty: rox.distinct_id

defaultValue: false

conditions:
  - allOf:
      - property:
          name: string-prop
          operator: regex
          operands:
            - "123"
    flagValue: false
  - allOf:
      - anyOf:
          - group:
              name: t
    flagValue: true
  - allOf:
      - flag:
          name: enableTutorialRomain
          value: "false"
    flagValue: false
  - allOf:
      - anyOf:
          - group:
              name: t
    flagValue: false
